export const MenuFixture = {
  MenuId: 16798,
  MenuVersionNumber: 354,
  VersionGuid: "e6220da2-c34a-4ea2-bb51-a3e190fc5f08",
  MenuSections: [
    {
      MenuSectionId: 194490,
      Name: "Mains",
      Description: null,
      DisplayOrder: 0,
      MenuItems: [
        {
          MenuItemId: 1299634,
          Name: "TestItem",
          Description: "",
          SpicinessRating: 0,
          Price: 10.0,
          DisplayOrder: 1,
          IsDeleted: false,
          Alcohol: false,
          Tags: [],
          PublicId: "0f19f344-2adc-4eb5-8b1e-3807ccf4d9ce",
          IsAvailable: true,
          MenuItemOptionSets: [],
          TaxRate: null,
          TaxRateId: null,
          TaxValue: 0.0,
          MenuSectionId: 194490,
          ImageName: "TTyzcRMqPdxtgGCrjjC3kX72tU.jpg",
          ImageUrl: "https://flipdish.imgix.net/TTyzcRMqPdxtgGCrjjC3kX72tU.jpg",
          CellAspectRatio: 1.3,
          CellLayoutType: 2,
          ActualPrice: 10.0,
          DisableVouchers: false,
          ExcludeFromVoucherDiscounting: false,
          DailySpecialHours: [],
          PriceCanIncrease: false,
          MenuItemMetadata: [],
        },
        {
          MenuItemId: 1299635,
          Name: "Pizza",
          Description: "",
          SpicinessRating: 0,
          Price: 10.0,
          DisplayOrder: 2,
          IsDeleted: false,
          Alcohol: false,
          Tags: [],
          PublicId: "8cf6d444-932c-429c-b898-b732f1b3dcaf",
          IsAvailable: true,
          MenuItemOptionSets: [],
          TaxRate: null,
          TaxRateId: null,
          TaxValue: 0.0,
          MenuSectionId: 194490,
          ImageName: "z7KOvSzCTNqntCjtrSuBwHNkTEo.jpg",
          ImageUrl:
            "https://flipdish.imgix.net/z7KOvSzCTNqntCjtrSuBwHNkTEo.jpg",
          CellAspectRatio: 1.3,
          CellLayoutType: 2,
          ActualPrice: 10.0,
          DisableVouchers: false,
          ExcludeFromVoucherDiscounting: false,
          DailySpecialHours: [],
          PriceCanIncrease: false,
          MenuItemMetadata: [],
        },
        {
          MenuItemId: 1299636,
          Name: "Burger",
          Description: "",
          SpicinessRating: 0,
          Price: 10.0,
          DisplayOrder: 3,
          IsDeleted: false,
          Alcohol: false,
          Tags: [],
          PublicId: "4315edcb-df23-415f-a763-438ac9b7e2fd",
          IsAvailable: true,
          MenuItemOptionSets: [
            {
              Name: null,
              MenuItemOptionSetId: 1494263,
              IsMasterOptionSet: false,
              DisplayOrder: 0,
              MinSelectCount: 0,
              MaxSelectCount: 4,
              IsDeleted: false,
              PublicId: "796c3858-3580-4c66-9bf3-e2f877d6605b",
              MenuItemOptionSetItems: [
                {
                  MenuItemOptionSetItemId: 13502402,
                  Name: "Cheese",
                  Price: 0.5,
                  TaxRateId: null,
                  TaxRate: null,
                  TaxValue: 0.0,
                  IsAvailable: true,
                  DisplayOrder: 0,
                  IsDeleted: false,
                  Tags: [],
                  NextMenuItemOptionSetId: null,
                  PublicId: "7a9f0344-ce7e-491e-824c-4ba319114b2f",
                  ImageName: null,
                  ImageUrl: null,
                  CellAspectRatio: 0.0,
                  CellLayoutType: 0,
                  OptionSetItemMetadata: [],
                },
                {
                  MenuItemOptionSetItemId: 13502403,
                  Name: "Bacon",
                  Price: 1.0,
                  TaxRateId: null,
                  TaxRate: null,
                  TaxValue: 0.0,
                  IsAvailable: true,
                  DisplayOrder: 1,
                  IsDeleted: false,
                  Tags: [],
                  NextMenuItemOptionSetId: null,
                  PublicId: "800760a4-1dc0-4db2-a552-2a7e80ec7b05",
                  ImageName: null,
                  ImageUrl: null,
                  CellAspectRatio: 0.0,
                  CellLayoutType: 0,
                  OptionSetItemMetadata: [],
                },
                {
                  MenuItemOptionSetItemId: 13502404,
                  Name: "Ketchup",
                  Price: 0.0,
                  TaxRateId: null,
                  TaxRate: null,
                  TaxValue: 0.0,
                  IsAvailable: true,
                  DisplayOrder: 2,
                  IsDeleted: false,
                  Tags: [],
                  NextMenuItemOptionSetId: null,
                  PublicId: "1944a354-7d46-4b21-b909-67f43d0cee4a",
                  ImageName: null,
                  ImageUrl: null,
                  CellAspectRatio: 0.0,
                  CellLayoutType: 0,
                  OptionSetItemMetadata: [],
                },
                {
                  MenuItemOptionSetItemId: 13502405,
                  Name: "Mayonnaise",
                  Price: 0.0,
                  TaxRateId: null,
                  TaxRate: null,
                  TaxValue: 0.0,
                  IsAvailable: true,
                  DisplayOrder: 3,
                  IsDeleted: false,
                  Tags: [],
                  NextMenuItemOptionSetId: null,
                  PublicId: "42bdea98-ed6b-4cf5-8ece-ed046b8e12c6",
                  ImageName: null,
                  ImageUrl: null,
                  CellAspectRatio: 0.0,
                  CellLayoutType: 0,
                  OptionSetItemMetadata: [],
                },
              ],
              ImageName: null,
              ImageUrl: null,
              CellAspectRatio: 0.0,
              CellLayoutType: 0,
              MinPrice: 0.0,
              MenuItemId: 1299636,
              MenuItemOptionSetMetadata: [],
            },
          ],
          TaxRate: null,
          TaxRateId: null,
          TaxValue: 0.0,
          MenuSectionId: 194490,
          ImageName: "FPY9VoQWKX8cItuATEYfxIu0WQ.jpg",
          ImageUrl: "https://flipdish.imgix.net/FPY9VoQWKX8cItuATEYfxIu0WQ.jpg",
          CellAspectRatio: 1.3,
          CellLayoutType: 2,
          ActualPrice: 10.0,
          DisableVouchers: false,
          ExcludeFromVoucherDiscounting: false,
          DailySpecialHours: [],
          PriceCanIncrease: false,
          MenuItemMetadata: [],
        },
      ],
      PublicId: "0dfc594c-5fd5-4a94-b7c0-b7c9dbc2d71e",
      IsDeleted: false,
      IsAvailable: true,
      IsHiddenFromUsers: false,
      ImageName: "5csY9WytLuMFRJQt29QkV94iAps.jpg",
      ImageUrl: "https://flipdish.imgix.net/5csY9WytLuMFRJQt29QkV94iAps.jpg",
      CellAspectRatio: 4.0,
      CellLayoutType: 0,
      MenuSectionAvailability: {
        AvailableTimes: [
          {
            BusinessHoursPeriodId: 474055,
            DayOfWeek: 1,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474056,
            DayOfWeek: 2,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474057,
            DayOfWeek: 3,
            StartTime: "11:30:00",
            Period: "02:10:00",
            StartTimeEarly: "11:30:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474058,
            DayOfWeek: 4,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474059,
            DayOfWeek: 5,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474060,
            DayOfWeek: 6,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
          {
            BusinessHoursPeriodId: 474061,
            DayOfWeek: 0,
            StartTime: "01:00:00",
            Period: "23:00:00",
            StartTimeEarly: "00:00:00",
            PeriodEarly: "00:00:00",
          },
        ],
        MenuSectionId: 194490,
        AvailabilityMode: 1,
      },
      ConcessionStoreId: null,
      MenuSectionMetadata: [],
    },
  ],
  MenuSectionBehaviour: 1,
  DisplaySectionLinks: true,
  ConcessionStores: [],
};
